db:
  host: 'localhost'
  user: 'root'
  pass: '123'
  post: 3363
  db: 'mc'

msg:
  login:
    chat: 'Pre prihlasenie napis /login <heslo>'
    title: ''
    subtitle: '/login <heslo>'
  register:
    chat: 'Pre registraciu napis /register <heslo> <heslo>'
    title: ''
    subtitle: '/register <heslo> <heslo>'
  timeout: 'Vyprsal casovy limit'

timeout: 40 # sec

spawnpoint:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0