db:
  host: 'localhost'
  user: 'root'
  pass: '123'
  port: 3306
  db: 'mc'

msg:
  login:
    chat: 'Pre prihlasenie napis /login <heslo>'
    title: ''
    subtitle: '/login <heslo>'
  register:
    chat: 'Pre registraciu napis /register <heslo> <heslo>'
    title: ''
    subtitle: '/register <heslo> <heslo>'
  timeout: 'Vyprsal casovy limit'
  log-a: 'Najprv sa musis zaregistrovat!'
  reg-a: 'Uz si zaregistrovany!'
  log-b: 'Zle heslo!'
  reg-b: 'Hesla sa nezhoduju!'
  log-c: 'Uspesne prihlaseny!'
  reg-c: 'Uspesne zaregistrovany!'
  log-d: 'Uz si prihlaseny!'
  reg-d: 'Heslo musi mat aspon 6 znakov!'

timeout: 40 # sec

spawnpoint:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0